on:
  workflow_dispatch:
jobs:
  build:
    name: Compile Sass
    runs-on: ubuntu-latest
    steps:
      - name: Clone from GitHub
        run: git clone https://github.com/ehanahamed/ehui.git
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: dart-lang/setup-dart@v1
      - name: Run npm script
        run: |
          cd ehui
          npm run build
      - name: Commit Changes
        run: |
          cd ehui
          git add .
          git config --global user.name "Ehan"
          git config --global user.email "ehanahamed@ehan.dev"
          git commit -m "Compile Sass"
      - name: Push to GitHub
        run: |
          cd ehui
          git push https://ehanahamed:${{ secrets.GH_TOKEN }}@github.com/ehanahamed/ehui.git --all
